language: node_js

cache:
    directories:
        - node_modules

node_js:
    - node
    - 7.0.0

sudo: false

matrix:
    fast_finish: true

before_install:
    - if [[ `npm -v` < 4.0.0 ]]; then npm i -g npm; fi
    - npm -v
    - npm update
    - npm prune
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 3;
      fi

install:
    - travis_retry npm i

postinstall:
    - npm run postinstall

script:
    - npm t --silent