language: node_js
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
node_js:
  - 7
  - 7.4 # VSCode 1.13.1
sudo: false
matrix:
  fast_finish: true
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
install:
  - travis_retry yarn upgrade
  - yarn run vscode:install
  - yarn run vscode:prepublish
script:
  - yarn test --silent
notifications:
  email: false
