language: node_js

cache:
    directories:
        - node_modules

node_js: node

sudo: false

matrix:
    fast_finish: true

before_install:
    - npm update
    - npm prune

install: travis_retry npm i

script:
    - npm run compile-build
    - npm run compile-highlight
    - node ./lib/build.js

test: npm test