language: node_js

cache:
    directories:
        - node_modules

node_js:
    - node
# Legacy Node; Bump engine requirements & drop when fail
    - 6
    - 5
    - 4

sudo: false

matrix:
    fast_finish: true

before_install:
# Update npm to latest version
    - if [[ `node -v` >= 7* ]]; then npm i -g npm; fi
    - npm -v
    - npm update
    - npm prune
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 3;
      fi

install:
    - travis_retry npm i

postinstall:
    - npm run postinstall

script:
    - npm t --silent