language: node_js

os:
#   - osx
    - linux

cache:
    directories:
        - node_modules

node_js:
    - node
# Legacy Node; Bump engine requirements & drop when fail
    - 6
    - 5
    - 4

sudo: false

matrix:
    fast_finish: true

before_install:
    - npm update
    - npm prune
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 3;
      fi

install:
    - travis_retry npm i
    - npm run vscode:install
    - npm run vscode:prepublish

script:
    - npm t --silent

after_success:
    - bash <(curl -s https://codecov.io/bash)