language: node_js
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
node_js:
  - node
  # Legacy; Deprecate when VS Code updates to Node 7+
  - 6
sudo: false
matrix:
  fast_finish: true
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - npm update
  - npm prune
install:
  - travis_retry npm i
  - npm run vscode:install
  - npm run vscode:prepublish
script:
  - npm t --silent
notifications:
  email: false
