environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "7.4"
platform:
  - x64
  - x86
cache:
  #- node_modules
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm update
  - npm prune
  - npm i
  - npm run vscode:install
  - npm run vscode:prepublish
test_script:
  - npm t --silent
build: off
