environment:
  matrix:
    - nodejs_version: "7.9.0"
platform:
  - x64
cache:
  - "%LOCALAPPDATA%\\Yarn"
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn
  - yarn vscode:install
  - yarn vscode:prepublish
test_script:
  - npm t --silent
build: off
