environment:
  matrix:
    # Latest node version
    - nodejs_version: ""
    - nodejs_version: "7"
    # Legacy; Deprecate when VS Code updates to Node 7+
    - nodejs_version: "6"
matrix:
  allow_failures:
    - nodejs_version: ""
platform:
  - x64
  - x86
cache:
  #- node_modules
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm update
  - npm prune
  - npm i
  - npm run vscode:install
  - npm run vscode:prepublish
test_script:
  - npm t --silent
build: off
